public class checkDataTypes {
    public void methodBoolean() {
    boolean checkBoolean = true;
    system.debug(checkBoolean);
    }

    public void menthodInteger(){
        integer varfirst = 1;
        integer varsecond =2;
        system.debug(varfirst);
        system.debug(varsecond);
    }

    public void stringMethod(){
        string varName = 'Name';
        string var2Name = 'Meruyert';
        system.debug(varName);
        system.debug(var2Name);
    }
}
