public class Primitivedata_Assignment {
   public void primitiveDataAssignmentMethod(){
    ID id = '0018Z00002f0HvaQAE';
    system.debug(id);
    
    string idOfAccounts = 'The following id belongs to Accounts.';
    system.debug(idOfAccounts);

    boolean check = true;
    system.debug(check);

    system.debug('The id is  '+id + 'The string is  '+ idOfAccounts + 'The boolean is  ' + check);
   }
}
